apiVersion: cilium.io/v2	
kind: CiliumIdentity	
metadata:	
  generation: 1	
  labels:	
    app: ocsinventory	
    app.kubernetes.io/instance: ocs-app	
    io.cilium.k8s.policy.cluster: default	
    io.cilium.k8s.policy.serviceaccount: default	
    io.kubernetes.pod.namespace: ocsinventoy	
  managedFields:	
    - apiVersion: cilium.io/v2	
      fieldsType: FieldsV1	
      fieldsV1:	
        f:metadata:	
          f:labels:	
            .: {}	
            f:app: {}	
            f:app.kubernetes.io/instance: {}	
            f:io.cilium.k8s.policy.cluster: {}	
            f:io.cilium.k8s.policy.serviceaccount: {}	
            f:io.kubernetes.pod.namespace: {}	
        f:security-labels:	
          .: {}	
          f:k8s:app: {}	
          f:k8s:app.kubernetes.io/instance: {}	
          f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: {}	
          f:k8s:io.cilium.k8s.policy.cluster: {}	
          f:k8s:io.cilium.k8s.policy.serviceaccount: {}	
          f:k8s:io.kubernetes.pod.namespace: {}	
      manager: cilium-agent	
      operation: Update	
      time: '2025-01-02T17:00:34Z'	
  name: '7532'	
  resourceVersion: '829441'	
  uid: 8cc43751-fcb8-40a8-9b98-9bc17f98c964	
security-labels:	
  k8s:app: ocsinventory	
  k8s:app.kubernetes.io/instance: ocs-app	
  k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: ocsinventoy	
  k8s:io.cilium.k8s.policy.cluster: default	
  k8s:io.cilium.k8s.policy.serviceaccount: default	
  k8s:io.kubernetes.pod.namespace: ocsinventoy	