apiVersion: v1
kind: ConfigMap
metadata:
  name: ocsinventory-config
data:
  # Adicione suas variáveis de configuração aqui
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "3306"
  DATABASE_USER: "ocs"
  DATABASE_PASS: "ocs"
  DATABASE_NAME: "ocs"