apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocsinventory-deployment
  labels:
    app: ocsinventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocsinventory
  template:
    metadata:
      labels:
        app: ocsinventory
    spec:
      containers:
      - name: ocsinventory-container
        image: ocsinventory/ocsinventory-docker-image:2.5
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: ocsinventory-config