apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocsinventory
  labels:
    app: ocsinventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocsinventory
  template:
    metadata:
      labels:
        app: ocsinventory
    spec:
      containers:
      - name: ocsinventory
        image: ocsinventory/ocsinventory-docker-image:2.5
        ports:
        - containerPort: 80
        env:
        - name: DB_SERVER
          value: "ocs-mysql"
        - name: MYSQL_DATABASE
          value: "ocs"
        - name: MYSQL_USER
          value: "ocsuser"
        - name: MYSQL_PASSWORD
          value: "ocs_password"
