apiVersion: v1
kind: Service
metadata:
  name: ocsinventory-service
  labels:
    app: ocsinventory
spec:
  selector:
    app: ocsinventory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP